/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as MarketRouteImport } from './routes/market'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedCartRouteImport } from './routes/_authenticated/cart'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedSellRouteImport } from './routes/_authenticated/sell'
import { Route as AuthenticatedWishlistRouteImport } from './routes/_authenticated/wishlist'
import { Route as ListingIdRouteImport } from './routes/listing.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketRoute = MarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCartRoute = AuthenticatedCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSellRoute = AuthenticatedSellRouteImport.update({
  id: '/sell',
  path: '/sell',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWishlistRoute = AuthenticatedWishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ListingIdRoute = ListingIdRouteImport.update({
  id: '/listing/$id',
  path: '/listing/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/categories': typeof CategoriesRoute
  '/market': typeof MarketRoute
  '/reset-password': typeof ResetPasswordRoute
  '/cart': typeof AuthenticatedCartRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/sell': typeof AuthenticatedSellRoute
  '/wishlist': typeof AuthenticatedWishlistRoute
  '/listing/$id': typeof ListingIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/categories': typeof CategoriesRoute
  '/market': typeof MarketRoute
  '/reset-password': typeof ResetPasswordRoute
  '/cart': typeof AuthenticatedCartRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/sell': typeof AuthenticatedSellRoute
  '/wishlist': typeof AuthenticatedWishlistRoute
  '/listing/$id': typeof ListingIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/categories': typeof CategoriesRoute
  '/market': typeof MarketRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/cart': typeof AuthenticatedCartRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/sell': typeof AuthenticatedSellRoute
  '/_authenticated/wishlist': typeof AuthenticatedWishlistRoute
  '/listing/$id': typeof ListingIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/categories'
    | '/market'
    | '/reset-password'
    | '/cart'
    | '/onboarding'
    | '/profile'
    | '/sell'
    | '/wishlist'
    | '/listing/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/categories'
    | '/market'
    | '/reset-password'
    | '/cart'
    | '/onboarding'
    | '/profile'
    | '/sell'
    | '/wishlist'
    | '/listing/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/categories'
    | '/market'
    | '/reset-password'
    | '/_authenticated/cart'
    | '/_authenticated/onboarding'
    | '/_authenticated/profile'
    | '/_authenticated/sell'
    | '/_authenticated/wishlist'
    | '/listing/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CategoriesRoute: typeof CategoriesRoute
  MarketRoute: typeof MarketRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ListingIdRoute: typeof ListingIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market': {
      id: '/market'
      path: '/market'
      fullPath: '/market'
      preLoaderRoute: typeof MarketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/cart': {
      id: '/_authenticated/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof AuthenticatedCartRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sell': {
      id: '/_authenticated/sell'
      path: '/sell'
      fullPath: '/sell'
      preLoaderRoute: typeof AuthenticatedSellRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/wishlist': {
      id: '/_authenticated/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof AuthenticatedWishlistRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/listing/$id': {
      id: '/listing/$id'
      path: '/listing/$id'
      fullPath: '/listing/$id'
      preLoaderRoute: typeof ListingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCartRoute: typeof AuthenticatedCartRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedSellRoute: typeof AuthenticatedSellRoute
  AuthenticatedWishlistRoute: typeof AuthenticatedWishlistRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCartRoute: AuthenticatedCartRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedSellRoute: AuthenticatedSellRoute,
  AuthenticatedWishlistRoute: AuthenticatedWishlistRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CategoriesRoute: CategoriesRoute,
  MarketRoute: MarketRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ListingIdRoute: ListingIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
